[package]
name = "narabe"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.80"
protocol = { version = "0.1.0", path = "../protocol" }
tools = { version = "0.1.0", path = "../tools" }
